### ISSUE TITLE
Metadata file can't be created on Linux OS because path separator is hardcoded

### ISSUE THREAD

**Issue by nemanja-d** [dina-heidar/saml2-authentication#10]
https://github.com/dina-heidar/saml2-authentication/blob/0ac4e202965388d843ee67a8d17cf4230ce9ab3b/SAML2Core/Configurations/Saml2PostConfigureOptions.cs#L372

**Comment by nemanja-d** [comment]
@dina-heidar  Hi, can you fix this or should I update it via fork and pull request? It's little bit rush for me, because I need this feature in one project...

**Comment by dina-heidar** [comment]
@nemanja-d you might need to do a fork for now until I add the new additional features I'm currently working on. 

I'd also really appreciate it if you could possibly do a pull request with recommended fix for Linux so it would be added to the new updated package.

**Comment by dina-heidar** [comment]
I published it now, it should, it appear shortly. Please let me know when you download and verify if everything is in working order so I can close this issue. There will be a new release soon which will include the fix as well. I Thank you !

**Comment by nemanja-d** [comment]
@dina-heidar It appears that package is not packaged well... When I download it from nuget.org, it returns me dll that is created on 2020-10-09... Can you please fix this and publish the right package...

**Comment by dina-heidar** [comment]
@nemanja-d i see what happened on my end. My apologies. I uploaded the correct one v3.1.3. Please let me know how it went. Thanks

**Comment by nemanja-d** [comment]
@dina-heidar now it works... thanks for support... If you would need in future anything else, feel free to contact me, I am always willing to help if there is time and space...

**Comment by dina-heidar** [comment]
Awesome!
