### ISSUE TITLE
Generate metadata xml

### ISSUE THREAD

**Issue by shamilgurban** [dina-heidar/saml2-authentication#12]
Is there any site for generating metadata xml for it or changing xml file is enough ?

**Comment by dina-heidar** [comment]
Hi @shamilgurban,  I don't currently have a site for it, it is planned though. For now, changing the xml file should be fine. If  using certificates  for signing the SAML Request and decrypting the SAML Response, please make sure the certificate information is also updated within the xml file..

**Comment by shamilgurban** [comment]
@dina-heidar I generated pem certificate and put it to new X509Certificate2(""), also added its key into <ns1:X509Certificate> tag of metadata. But I don't know how to generate Signature Value and Digest Value. CheckSignature method return false :( How can I set value for it ?
