### ISSUE TITLE
Intermittent "Assertion signature is not valid" exceptions

### ISSUE THREAD

**Issue by fokkog** [dina-heidar/saml2-authentication#13]
We are using (a fork of) your library in an application of ours. During real-world validation, it was found that SSO intermittently fails with stated exception. After a lot of debugging it was found that the SAML response contains this line:
`<Assertion ID="_615964bb-8e35-4c84-a169-eb8c9e315400" IssueInstant="2021-08-02T06:34:48.760Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">`

After deserialization and (re)serialization by Saml2Service.GetAssertion(), the trailing zero in the timestamp has disappeared hence signature validation gets to see:
`<Assertion ID="_615964bb-8e35-4c84-a169-eb8c9e315400" IssueInstant="2021-08-02T06:34:48.76Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">`

Does this ring a bell?

**Comment by dina-heidar** [comment]
Hi @fokkog- I'm not aware of this specific issue. Let me ask you a few questions. 
What Idp are you using? 
What type of authentication are you using with the Idp? Forms or Windows? I've seen issues with windows authentication. I've been working on a fix for that.

**Comment by fokkog** [comment]
The Idp that provided quoted line is Azure AD. Login to Azure AD is form-based.

FYI we have the same intermittent exception with ADFS, but we haven't yet managed to capture a SAML response that triggers it. Hence for ADFS we cannot be sure it's the exact same root cause.
Having said that, the assertion round-tripping approach strikes me as risky. The deserialised AssertionType contains various DateTime objects with no clue about their original representation/precision. I don't find it surprising that the serialisation by Saml2Service.GetAssertion() can lead to a different payload, thus breaking the signature validation.
Only assertion signature validation suffers from this, not response signature validation because that works with the original DOM object.

**Comment by dina-heidar** [comment]
I'm not sure what the cause could be. We are ADFS with signed assertion and had no issues at all when using forms authentication. 

The only issue I have seen before is when using windows authentication while logging out then logging in - which I am working on code to address. 

Has the IdP admin (Azure and ADFS) checked the logs to see what is causing it? Also please check the SAML response from ADFS and compare.

**Comment by fokkog** [comment]
Thanks for your responses!
In the meantime we've been able to intercept failing and passing SAML responses from ADFS also. It's the exact same issue. If the IssueInstant milliseconds end in '0' (statistically 1 in every 10 logins) then assertion signature validation fails and we get the exception. Otherwise it passes and all is fine. I can share the SAML responses if you are interested, but I won't attach them here since they contain sensitive data.
I'd say it's a clear bug and I'm surprised we are the first/only library user to suffer from this. Maybe there is something environmental at work. In any case we'll try to fix it in our private fork by doing signature validation on the original Assertion payload instead of the recreated one.

**Comment by fokkog** [comment]
Fixed in our fork. Considering that other library users are apparently not affected, I will close this issue.
