### ISSUE TITLE
Can I use this with JWT authentication?

### ISSUE THREAD

**Issue by mkgn** [dina-heidar/saml2-authentication#9]
Should there be any change in the authentication flow if I use Asp.net Identity and JWT?

**Comment by dina-heidar** [comment]
SAML is based on XML and is  used commonly in protocols like SAML-P, WS-Trust and WS-Federation while JWTs are based on JSON and is used in new authentication and authorization protocols like OpenID Connect (OIDC) and OAuth 2.0.

The middleware will extract the claims from the SAML response. From there, you will either need to create the JWT in your code or use a 3rd party identity management tool (e.g IdentityServer with Asp.Net Identity) which can generate a signed JWT based on the incoming SAML response and send it to the client.
